name: Daily Firestore Cache

on:
  push:
    branches:
      - backend
    paths:
      - 'backend/**'
      - '.github/workflows/docker-build.yaml'
  # schedule:
  #   - cron: '0 0 * * *' # Run daily at midnight

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend/

    - name: Create Secrets File
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RED_CORAL_MAP }}' > creds.json
      working-directory: backend/

    - name: Run cache script
      run: |
        python cache_script.py
      working-directory: backend/
